import os
head=''' // generated by genMajorane.py
#include "HadronInfo/Majorana.h"
bool selfConjugate(int pid) { 
    switch (pid) {
'''

def gen(s):
    code = s
    for line in open("selfconjudate.txt", 'r').readlines():
        pid = line.split()[0]
        code += "case {}: return true;\n".format(pid)
    code += "default: return false; } }\n"
    return code
f = open("Majorana.cpp", 'w')
f.write(gen(head))
f.close()
os.system("clang-format -i Majorana.cpp")
